### ISSUE TITLE
[Bug] In edit mode, I can only insert text

### ISSUE THREAD

**Issue by CrowderSoup** [SpencerCDixon/exocortex#13]
Hey, tried in Firefox and Chrome. When I'm in edit mode I can insert text, but pressing enter doesn't give me a new line, and backspace doesn't delete.

**Comment by sbramin** [comment]
Ditto, `CTRL` S/P/E in Chrome on Linux are already bound to browser actions thus don't get caught by the the app. And as above can't delete or new line.

**Comment by SpencerCDixon** [comment]
Should be fixed now in `0.2.3`

Royally messed things up few weeks ago when I refactored to redux and then was pressured to release from friend without doing proper QA... 🙃 

`brew upgrade exocortex`
