### ISSUE TITLE
Fix copy/paste into slate editor

### ISSUE THREAD

**Issue by SpencerCDixon** [SpencerCDixon/exocortex#6]

**Comment by ajambrosino** [comment]
Was about to add an issue here:

Command-V seemed to 'save and close?' the doc, but Edit > Paste worked fine

**Comment by SpencerCDixon** [comment]
Yeah removed the 'v' override, should be working if you `brew update exocortex`.  Still doesn't let me `cmd + delete` a line though which is super annoying.  Prob spend a day learning Slate some weekend and build a better editor.. for now I jsut use vim + markdown
