### ISSUE TITLE
Add Linux distributions (I don't use linux so low priority for me..)

### ISSUE THREAD

**Issue by SpencerCDixon** [SpencerCDixon/exocortex#8]

**Comment by zelenin** [comment]
i don't know what is Tux, but this version works in Ubuntu.

**Comment by SpencerCDixon** [comment]
Cool, glad to hear!  Prob just gonna close for now unless someone has specific request

**Comment by oren** [comment]
@zelenin on ubuntu (firefox) the following keys don't work for me: preview, save, and insert. On Chrome insert works. Interesting to hear that it works for you. What browser do you use?
